### ISSUE TITLE
A string with format uuid generates code that doesn't compile

### ISSUE THREAD

**Issue by inve1** [phiz71/vertx-swagger#61]
a route with a parameter like this

```yaml
  uuidParam:
    name: some_uuid
    description: a uuid
    in: path
    required: true
    type: string
    format: uuid
```

generates this code in the DefaultApiVerticle

```java
UUID someUuid = message.body().getString("some_uuid");
```

which obviously doesn't compile. For now I have a not great workaround here https://github.com/inve1/vertx-swagger/commit/58e0ea005381bf486f12f3cef28fb12a01a15e73
but this is the first time I've looked at swagger-codegen or mustache, so perhaps there's a nicer way (and I haven't looked into other string/format combinations that might generate other types in java).  

Seems like mustache doesn't support conditionals so the only other way to do it would be a runtime detection which kinda sounds worse (you'd end up doing that detection for real strings as well on each call? meh)

Anyway, it's broken.. thought I'd report it
