### ISSUE TITLE
Required schema properties not returning http error code

### ISSUE THREAD

**Issue by StephenFox1995** [phiz71/vertx-swagger#83]
I'm new enough to Swagger, so this may not be part of the spec so correct me if im wrong.
But i'm trying to force that `schema` properties are required through the `swagger-router` module, and if required properties are not found then some 4xx http error code is returned. 

For example:
```  
/test
  post:
    summary: x
      operationId: test
      required: true
      parameters:
        schema:
          type: object
          required:
            - lat
            - long
          properties:
            lat:
              type: number
            long:
              type: number
```

When I send an empty `{}` body without the required field properties `lat` or `lng`, the message is still sent to my event bus consumer for that endpoint, instead of returning  a http error code. Is this an issue or is this the expected behaviour?
